build against caddy master branch to resolve dependency failure
mholt/caddy@53e117802fedd is currently in master and resolves a
dependency failure due to xenolf/lego@72914df00f, which
added "OCSP must staple" support.

Resolves build failure with caddy v0.9.3:

    ../caddytls/client.go:197: not enough arguments in call to c.acmeClient.ObtainCertificate
    ../caddytls/client.go:285: not enough arguments in call to c.acmeClient.RenewCertificate